### ISSUE TITLE
README处链接指向不正确

### ISSUE THREAD

**Issue by 493505110** [CubecraftDevelopment/Cubecraft#1]
![image](https://github.com/ProtonGameStudio/Cubecraft/assets/29498336/1750a865-0c70-42c8-b8e0-3598f638dd0d)
这些链接指向的仍是https://github.com/othneildrew/Best-README-Template

**Comment by 493505110** [comment]
并且,jar依赖文件不应放在git仓库,应在gradle处导入依赖

**Comment by hehe1005566889** [comment]
你搁着自导自演呢

**Comment by 493505110** [comment]
？

**Comment by Grass-block** [comment]
感谢!
最近忙着做quantum3d和重构了史山一般的渲染系统，实在没时间修这玩意儿。
将在下次推送时修复这些问题

**Comment by Grass-block** [comment]
> 并且,jar依赖文件不应放在git仓库,应在gradle处导入依赖

已经抽离一部分库到github packages了

**Comment by Grass-block** [comment]
我可以关了issue了吧
